#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef IPOSGOSDK_SWIFT_H
#define IPOSGOSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IposgoSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("CAPKDB")
@interface CAPKDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class NSString;

@interface CAPKDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable expiredate;
@property (nonatomic, copy) NSString * _Nullable expoent;
@property (nonatomic, copy) NSString * _Nullable hashX;
@property (nonatomic, copy) NSString * _Nullable idx;
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, copy) NSString * _Nullable rid;
@property (nonatomic, copy) NSString * _Nullable taxmcr;
@property (nonatomic, copy) NSString * _Nullable taxppr;
@end


SWIFT_CLASS_NAMED("DEVICEINFO")
@interface DEVICEINFO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class NSDate;

@interface DEVICEINFO (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable appbuildno;
@property (nonatomic, copy) NSString * _Nullable appversion;
@property (nonatomic, copy) NSString * _Nullable bundleid;
@property (nonatomic, copy) NSDate * _Nullable hbtimestamp;
@property (nonatomic, copy) NSString * _Nullable jwtoken;
@end


SWIFT_CLASS_NAMED("DPDB")
@interface DPDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface DPDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable app_sign;
@property (nonatomic, copy) NSString * _Nullable build;
@property (nonatomic, copy) NSString * _Nullable model;
@property (nonatomic, copy) NSString * _Nullable tpn;
@end


SWIFT_CLASS_NAMED("EMVDB")
@interface EMVDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface EMVDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable aut_aid_optn;
@property (nonatomic, copy) NSString * _Nullable aut_aid_sel;
@property (nonatomic, copy) NSString * _Nullable c_non_dce_lt;
@property (nonatomic, copy) NSString * _Nullable cdce_lt;
@property (nonatomic, copy) NSString * _Nullable cntry_cde;
@property (nonatomic, copy) NSString * _Nullable crncy_cde;
@property (nonatomic, copy) NSString * _Nullable crncy_exp;
@property (nonatomic, copy) NSString * _Nullable ctx_lt;
@property (nonatomic, copy) NSString * _Nullable cvm_cap_no_req;
@property (nonatomic, copy) NSString * _Nullable cvm_cap_req;
@property (nonatomic, copy) NSString * _Nullable fal_cnt;
@property (nonatomic, copy) NSString * _Nullable fall_bck;
@property (nonatomic, copy) NSString * _Nullable ker_con;
@property (nonatomic, copy) NSString * _Nullable pin_byps_cr;
@property (nonatomic, copy) NSString * _Nullable tac_default;
@property (nonatomic, copy) NSString * _Nullable tac_denial;
@property (nonatomic, copy) NSString * _Nullable tac_onlne;
@property (nonatomic, copy) NSString * _Nullable ter_cap;
@end


SWIFT_CLASS_NAMED("FEEDB")
@interface FEEDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface FEEDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable cf_afd;
@property (nonatomic, copy) NSString * _Nullable cf_aft;
@property (nonatomic, copy) NSString * _Nullable cf_amt;
@property (nonatomic, copy) NSString * _Nullable cf_dfc;
@property (nonatomic, copy) NSString * _Nullable cf_dl;
@property (nonatomic, copy) NSString * _Nullable cf_mcr;
@property (nonatomic, copy) NSString * _Nullable cf_per;
@property (nonatomic, copy) NSString * _Nullable cf_ppr;
@property (nonatomic, copy) NSString * _Nullable cf_tx_amt;
@property (nonatomic, copy) NSString * _Nullable csh_msg_in_crd;
@property (nonatomic, copy) NSString * _Nullable csh_msg_in_csh;
@property (nonatomic, copy) NSString * _Nullable dcaft;
@property (nonatomic, copy) NSString * _Nullable dpadjustprice;
@property (nonatomic, copy) NSString * _Nullable dpamt;
@property (nonatomic, copy) NSString * _Nullable dpftl;
@property (nonatomic, copy) NSString * _Nullable dppasswordap;
@property (nonatomic, copy) NSString * _Nullable dppcd;
@property (nonatomic, copy) NSString * _Nullable dpper;
@property (nonatomic, copy) NSString * _Nullable dpprompt;
@property (nonatomic, copy) NSString * _Nullable dpsb;
@property (nonatomic, copy) NSString * _Nullable dptaxonfee;
@property (nonatomic, copy) NSString * _Nullable f_typ;
@property (nonatomic, copy) NSString * _Nullable fee;
@property (nonatomic, copy) NSString * _Nullable mpaft;
@property (nonatomic, copy) NSString * _Nullable mpamt;
@property (nonatomic, copy) NSString * _Nullable mpdfc;
@property (nonatomic, copy) NSString * _Nullable mpdl;
@property (nonatomic, copy) NSString * _Nullable mpmcr;
@property (nonatomic, copy) NSString * _Nullable mpper;
@property (nonatomic, copy) NSString * _Nullable mpppr;
@property (nonatomic, copy) NSString * _Nullable mptaxonfee;
@property (nonatomic, copy) NSString * _Nullable mptxamt;
@property (nonatomic, copy) NSString * _Nullable save_msg_lbl;
@property (nonatomic, copy) NSString * _Nullable sramtc;
@property (nonatomic, copy) NSString * _Nullable srast;
@property (nonatomic, copy) NSString * _Nullable srdfcus;
@property (nonatomic, copy) NSString * _Nullable srdlc;
@property (nonatomic, copy) NSString * _Nullable srmatc;
@property (nonatomic, copy) NSString * _Nullable srmcr;
@property (nonatomic, copy) NSString * _Nullable srper;
@property (nonatomic, copy) NSString * _Nullable srperc;
@property (nonatomic, copy) NSString * _Nullable srppr;
@property (nonatomic, copy) NSString * _Nullable srtxzmt;
@property (nonatomic, copy) NSString * _Nullable tax_on_fee;
@property (nonatomic, copy) NSString * _Nullable tcdadjustprice;
@property (nonatomic, copy) NSString * _Nullable tcdaet;
@property (nonatomic, copy) NSString * _Nullable tcdaft;
@property (nonatomic, copy) NSString * _Nullable tcdamt;
@property (nonatomic, copy) NSString * _Nullable tcdcalculator;
@property (nonatomic, copy) NSString * _Nullable tcdmsrp;
@property (nonatomic, copy) NSString * _Nullable tcdmsrplabel;
@property (nonatomic, copy) NSString * _Nullable tcdpcd;
@property (nonatomic, copy) NSString * _Nullable tcdpdctext;
@property (nonatomic, copy) NSString * _Nullable tcdper;
@property (nonatomic, copy) NSString * _Nullable tcdpil;
@property (nonatomic, copy) NSString * _Nullable tcdpwdpradjustopt;
@property (nonatomic, copy) NSString * _Nullable tcdsavmsg;
@property (nonatomic, copy) NSString * _Nullable tcdsavmsglable;
@property (nonatomic, copy) NSString * _Nullable tcdsb;
@property (nonatomic, copy) NSString * _Nullable tcdsd;
@property (nonatomic, copy) NSString * _Nullable tcdskipitem;
@property (nonatomic, copy) NSString * _Nullable tcdtaxonfee;
@property (nonatomic, copy) NSString * _Nullable tcdtdebcash;
@end


SWIFT_CLASS_NAMED("FEEPRFDB")
@interface FEEPRFDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface FEEPRFDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable w_fee;
@property (nonatomic, copy) NSString * _Nullable wo_fee;
@end


SWIFT_CLASS_NAMED("HBDB")
@interface HBDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface HBDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSDate * _Nullable hbTimeStamp;
@end


SWIFT_CLASS_NAMED("HOSTCONFIGDB")
@interface HOSTCONFIGDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface HOSTCONFIGDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable payurl;
@property (nonatomic, copy) NSString * _Nullable portalport;
@property (nonatomic, copy) NSString * _Nullable portalurl;
@property (nonatomic, copy) NSString * _Nullable sensepassurl;
@property (nonatomic, copy) NSString * _Nullable socketsensepassurl;
@property (nonatomic, copy) NSString * _Nullable steamport;
@property (nonatomic, copy) NSString * _Nullable steamurl;
@property (nonatomic, copy) NSString * _Nullable txnport;
@property (nonatomic, copy) NSString * _Nullable txnurl;
@end


SWIFT_CLASS_NAMED("INTEGDB")
@interface INTEGDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface INTEGDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable authtoken;
@property (nonatomic, copy) NSString * _Nullable brnchid;
@property (nonatomic, copy) NSString * _Nullable clntid;
@property (nonatomic, copy) NSString * _Nullable clntsertid;
@property (nonatomic, copy) NSString * _Nullable cryptopago;
@property (nonatomic, copy) NSString * _Nullable gifthost;
@property (nonatomic, copy) NSString * _Nullable mrchntid;
@property (nonatomic, copy) NSString * _Nullable qrcode;
@property (nonatomic, copy) NSString * _Nullable sanpass;
@property (nonatomic, copy) NSString * _Nullable sanpasstyp;
@property (nonatomic, copy) NSString * _Nullable sensepasstimeout;
@property (nonatomic, copy) NSString * _Nullable typintg;
@end


SWIFT_CLASS_NAMED("MISCDB")
@interface MISCDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class NSObject;

@interface MISCDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable app_download_timer;
@property (nonatomic, copy) NSString * _Nullable com_timeout;
@property (nonatomic, copy) NSString * _Nullable cust_logo;
@property (nonatomic, copy) NSString * _Nullable dsl_timer;
@property (nonatomic, copy) NSString * _Nullable e_promo_id;
@property (nonatomic, copy) NSString * _Nullable e_rcpt_img_url;
@property (nonatomic, copy) NSString * _Nullable e_rcpt_msg;
@property (nonatomic, copy) NSString * _Nullable e_rcpt_titl;
@property (nonatomic, copy) NSString * _Nullable e_rcpt_url;
@property (nonatomic, copy) NSString * _Nullable logourl;
@property (nonatomic, copy) NSString * _Nullable m_pass_set;
@property (nonatomic, copy) NSString * _Nullable p_promo_id;
@property (nonatomic, copy) NSString * _Nullable pap_rcpt_msg;
@property (nonatomic, copy) NSString * _Nullable pap_rcpt_titl;
@property (nonatomic, copy) NSString * _Nullable pap_rcpt_url;
@property (nonatomic, copy) NSString * _Nullable promo_id;
@property (nonatomic, copy) NSString * _Nullable qrtimer;
@property (nonatomic, copy) NSString * _Nullable sc_idl_timer;
@property (nonatomic, strong) NSObject * _Nullable sostype;
@property (nonatomic, copy) NSString * _Nullable sttl_tme_ot;
@property (nonatomic, copy) NSString * _Nullable trw_time;
@property (nonatomic, copy) NSString * _Nullable warn_msg;
@end


SWIFT_CLASS_NAMED("RECEIPTDB")
@interface RECEIPTDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface RECEIPTDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, strong) NSObject * _Nullable cr_c;
@property (nonatomic, copy) NSString * _Nullable dis;
@property (nonatomic) BOOL email;
@property (nonatomic, copy) NSString * _Nullable f1;
@property (nonatomic, copy) NSString * _Nullable f2;
@property (nonatomic, copy) NSString * _Nullable h1;
@property (nonatomic, copy) NSString * _Nullable h2;
@property (nonatomic, copy) NSString * _Nullable h3;
@property (nonatomic, copy) NSString * _Nullable h4;
@property (nonatomic) BOOL sms;
@end


SWIFT_CLASS_NAMED("REVERSALSTATUSDB")
@interface REVERSALSTATUSDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface REVERSALSTATUSDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable appFlowLog;
@property (nonatomic, copy) NSString * _Nullable lastTxnStatus;
@property (nonatomic, copy) NSString * _Nullable reversalAttemptCount;
@property (nonatomic, copy) NSString * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable tpn;
@property (nonatomic, copy) NSString * _Nullable traceNo;
@property (nonatomic, copy) NSString * _Nullable txRefNo;
@end


SWIFT_CLASS_NAMED("SETLDB")
@interface SETLDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface SETLDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable settleop;
@property (nonatomic, copy) NSString * _Nullable sm;
@end


SWIFT_CLASS_NAMED("SignatureUploadParam")
@interface SignatureUploadParam : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface SignatureUploadParam (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable additionalnntrymode;
@property (nonatomic, copy) NSString * _Nullable aid;
@property (nonatomic, copy) NSString * _Nullable aifname;
@property (nonatomic, copy) NSString * _Nullable amount;
@property (nonatomic, copy) NSString * _Nullable appname;
@property (nonatomic, copy) NSString * _Nullable baseimage;
@property (nonatomic, copy) NSString * _Nullable batchnum;
@property (nonatomic, copy) NSString * _Nullable buildnumber;
@property (nonatomic, copy) NSString * _Nullable cardNumber;
@property (nonatomic, copy) NSString * _Nullable cardType;
@property (nonatomic, copy) NSString * _Nullable commmedia;
@property (nonatomic, copy) NSString * _Nullable customfeelabel;
@property (nonatomic, copy) NSString * _Nullable customField;
@property (nonatomic, copy) NSString * _Nullable dateTime;
@property (nonatomic, copy) NSString * _Nullable description_;
@property (nonatomic, copy) NSString * _Nullable devicemodelId;
@property (nonatomic, copy) NSString * _Nullable discfabel;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable entrylegend;
@property (nonatomic, copy) NSString * _Nullable hTxId;
@property (nonatomic, copy) NSString * _Nullable inventoryCardArrayString;
@property (nonatomic, copy) NSString * _Nullable inventoryItems;
@property (nonatomic, copy) NSString * _Nullable invoiceNo;
@property (nonatomic) BOOL isibs;
@property (nonatomic, copy) NSString * _Nullable itemDetails;
@property (nonatomic, copy) NSString * _Nullable localtaxLabel;
@property (nonatomic, copy) NSString * _Nullable merchantfeefabel;
@property (nonatomic, copy) NSString * _Nullable paymenttype;
@property (nonatomic, copy) NSString * _Nullable phonenumber;
@property (nonatomic, copy) NSString * _Nullable pinstatus;
@property (nonatomic, copy) NSString * _Nullable postype;
@property (nonatomic, copy) NSString * _Nullable refundpolicy1;
@property (nonatomic, copy) NSString * _Nullable refundpolicy2;
@property (nonatomic, copy) NSString * _Nullable rrn;
@property (nonatomic, copy) NSString * _Nullable selectedPayment;
@property (nonatomic, copy) NSString * _Nullable statetaxLabel;
@property (nonatomic, copy) NSString * _Nullable surveyans;
@property (nonatomic, copy) NSString * _Nullable surveyquest;
@property (nonatomic, copy) NSString * _Nullable taglabel;
@property (nonatomic, copy) NSString * _Nullable tagvalue;
@property (nonatomic, copy) NSString * _Nullable tpn;
@property (nonatomic, copy) NSString * _Nullable traceNo;
@property (nonatomic, copy) NSString * _Nullable transactionType;
@property (nonatomic, copy) NSString * _Nullable transType;
@property (nonatomic, copy) NSString * _Nullable txduration;
@property (nonatomic, copy) NSString * _Nullable txid;
@property (nonatomic, copy) NSString * _Nullable txRefNo;
@property (nonatomic) BOOL uploadStatus;
@property (nonatomic, copy) NSString * _Nullable verficationline1;
@property (nonatomic, copy) NSString * _Nullable verificationline2;
@end


SWIFT_CLASS_NAMED("TIPTAXDB")
@interface TIPTAXDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface TIPTAXDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable ltax;
@property (nonatomic, copy) NSString * _Nullable max_ta;
@property (nonatomic, copy) NSString * _Nullable max_tp;
@property (nonatomic, copy) NSString * _Nullable s1;
@property (nonatomic, copy) NSString * _Nullable s2;
@property (nonatomic, copy) NSString * _Nullable s3;
@property (nonatomic, copy) NSString * _Nullable s4;
@property (nonatomic, copy) NSString * _Nullable stax;
@property (nonatomic, copy) NSString * _Nullable tax;
@property (nonatomic, copy) NSString * _Nullable tax1lable;
@property (nonatomic, copy) NSString * _Nullable tax2lable;
@property (nonatomic, copy) NSString * _Nullable taxmcr;
@property (nonatomic, copy) NSString * _Nullable taxppr;
@property (nonatomic, copy) NSString * _Nullable tip;
@property (nonatomic, copy) NSString * _Nullable tip_typ;
@property (nonatomic, copy) NSString * _Nullable ts_pap;
@property (nonatomic, copy) NSString * _Nullable ts_pos;
@end


SWIFT_CLASS_NAMED("TRANSACTIONDB")
@interface TRANSACTIONDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface TRANSACTIONDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable avs;
@property (nonatomic, copy) NSString * _Nullable batchpassword;
@property (nonatomic, strong) NSObject * _Nullable card_type;
@property (nonatomic, copy) NSString * _Nullable preauthpassword;
@property (nonatomic, copy) NSString * _Nullable presalepassword;
@property (nonatomic, copy) NSString * _Nullable printsavemsg;
@property (nonatomic, copy) NSString * _Nullable refundpassword;
@property (nonatomic, copy) NSString * _Nullable reportpassword;
@property (nonatomic, copy) NSString * _Nullable reprintpassword;
@property (nonatomic, copy) NSString * _Nullable save_msg_lbl;
@property (nonatomic, copy) NSString * _Nullable sl;
@property (nonatomic, copy) NSString * _Nullable ss;
@property (nonatomic, copy) NSString * _Nullable ticketpassword;
@property (nonatomic, copy) NSString * _Nullable tipadjustpassword;
@property (nonatomic, strong) NSObject * _Nullable tx_mode;
@property (nonatomic, strong) NSObject * _Nullable tx_type;
@property (nonatomic, copy) NSString * _Nullable upgradepassword;
@property (nonatomic, copy) NSString * _Nullable voidpassword;
@end



SWIFT_CLASS_NAMED("VALADDDB")
@interface VALADDDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface VALADDDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable cussurv;
@property (nonatomic, copy) NSString * _Nullable invdefault;
@property (nonatomic, copy) NSString * _Nullable invibs;
@property (nonatomic, copy) NSString * _Nullable savetageach;
@property (nonatomic, copy) NSString * _Nullable sur_q;
@property (nonatomic, copy) NSString * _Nullable taginvoicekey;
@property (nonatomic, copy) NSString * _Nullable taginvoiceno;
@property (nonatomic, copy) NSString * _Nullable taginvoiceopt;
@property (nonatomic, copy) NSString * _Nullable taglabl;
@property (nonatomic, copy) NSString * _Nullable taglablkey;
@property (nonatomic, copy) NSString * _Nullable taglablopt;
@property (nonatomic, copy) NSString * _Nullable tagtableid;
@property (nonatomic, copy) NSString * _Nullable tagtablekey;
@property (nonatomic, copy) NSString * _Nullable tagtableopt;
@property (nonatomic, copy) NSString * _Nullable tagtx;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef IPOSGOSDK_SWIFT_H
#define IPOSGOSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IposgoSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("CAPKDB")
@interface CAPKDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class NSString;

@interface CAPKDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable expiredate;
@property (nonatomic, copy) NSString * _Nullable expoent;
@property (nonatomic, copy) NSString * _Nullable hashX;
@property (nonatomic, copy) NSString * _Nullable idx;
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, copy) NSString * _Nullable rid;
@property (nonatomic, copy) NSString * _Nullable taxmcr;
@property (nonatomic, copy) NSString * _Nullable taxppr;
@end


SWIFT_CLASS_NAMED("DEVICEINFO")
@interface DEVICEINFO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class NSDate;

@interface DEVICEINFO (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable appbuildno;
@property (nonatomic, copy) NSString * _Nullable appversion;
@property (nonatomic, copy) NSString * _Nullable bundleid;
@property (nonatomic, copy) NSDate * _Nullable hbtimestamp;
@property (nonatomic, copy) NSString * _Nullable jwtoken;
@end


SWIFT_CLASS_NAMED("DPDB")
@interface DPDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface DPDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable app_sign;
@property (nonatomic, copy) NSString * _Nullable build;
@property (nonatomic, copy) NSString * _Nullable model;
@property (nonatomic, copy) NSString * _Nullable tpn;
@end


SWIFT_CLASS_NAMED("EMVDB")
@interface EMVDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface EMVDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable aut_aid_optn;
@property (nonatomic, copy) NSString * _Nullable aut_aid_sel;
@property (nonatomic, copy) NSString * _Nullable c_non_dce_lt;
@property (nonatomic, copy) NSString * _Nullable cdce_lt;
@property (nonatomic, copy) NSString * _Nullable cntry_cde;
@property (nonatomic, copy) NSString * _Nullable crncy_cde;
@property (nonatomic, copy) NSString * _Nullable crncy_exp;
@property (nonatomic, copy) NSString * _Nullable ctx_lt;
@property (nonatomic, copy) NSString * _Nullable cvm_cap_no_req;
@property (nonatomic, copy) NSString * _Nullable cvm_cap_req;
@property (nonatomic, copy) NSString * _Nullable fal_cnt;
@property (nonatomic, copy) NSString * _Nullable fall_bck;
@property (nonatomic, copy) NSString * _Nullable ker_con;
@property (nonatomic, copy) NSString * _Nullable pin_byps_cr;
@property (nonatomic, copy) NSString * _Nullable tac_default;
@property (nonatomic, copy) NSString * _Nullable tac_denial;
@property (nonatomic, copy) NSString * _Nullable tac_onlne;
@property (nonatomic, copy) NSString * _Nullable ter_cap;
@end


SWIFT_CLASS_NAMED("FEEDB")
@interface FEEDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface FEEDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable cf_afd;
@property (nonatomic, copy) NSString * _Nullable cf_aft;
@property (nonatomic, copy) NSString * _Nullable cf_amt;
@property (nonatomic, copy) NSString * _Nullable cf_dfc;
@property (nonatomic, copy) NSString * _Nullable cf_dl;
@property (nonatomic, copy) NSString * _Nullable cf_mcr;
@property (nonatomic, copy) NSString * _Nullable cf_per;
@property (nonatomic, copy) NSString * _Nullable cf_ppr;
@property (nonatomic, copy) NSString * _Nullable cf_tx_amt;
@property (nonatomic, copy) NSString * _Nullable csh_msg_in_crd;
@property (nonatomic, copy) NSString * _Nullable csh_msg_in_csh;
@property (nonatomic, copy) NSString * _Nullable dcaft;
@property (nonatomic, copy) NSString * _Nullable dpadjustprice;
@property (nonatomic, copy) NSString * _Nullable dpamt;
@property (nonatomic, copy) NSString * _Nullable dpftl;
@property (nonatomic, copy) NSString * _Nullable dppasswordap;
@property (nonatomic, copy) NSString * _Nullable dppcd;
@property (nonatomic, copy) NSString * _Nullable dpper;
@property (nonatomic, copy) NSString * _Nullable dpprompt;
@property (nonatomic, copy) NSString * _Nullable dpsb;
@property (nonatomic, copy) NSString * _Nullable dptaxonfee;
@property (nonatomic, copy) NSString * _Nullable f_typ;
@property (nonatomic, copy) NSString * _Nullable fee;
@property (nonatomic, copy) NSString * _Nullable mpaft;
@property (nonatomic, copy) NSString * _Nullable mpamt;
@property (nonatomic, copy) NSString * _Nullable mpdfc;
@property (nonatomic, copy) NSString * _Nullable mpdl;
@property (nonatomic, copy) NSString * _Nullable mpmcr;
@property (nonatomic, copy) NSString * _Nullable mpper;
@property (nonatomic, copy) NSString * _Nullable mpppr;
@property (nonatomic, copy) NSString * _Nullable mptaxonfee;
@property (nonatomic, copy) NSString * _Nullable mptxamt;
@property (nonatomic, copy) NSString * _Nullable save_msg_lbl;
@property (nonatomic, copy) NSString * _Nullable sramtc;
@property (nonatomic, copy) NSString * _Nullable srast;
@property (nonatomic, copy) NSString * _Nullable srdfcus;
@property (nonatomic, copy) NSString * _Nullable srdlc;
@property (nonatomic, copy) NSString * _Nullable srmatc;
@property (nonatomic, copy) NSString * _Nullable srmcr;
@property (nonatomic, copy) NSString * _Nullable srper;
@property (nonatomic, copy) NSString * _Nullable srperc;
@property (nonatomic, copy) NSString * _Nullable srppr;
@property (nonatomic, copy) NSString * _Nullable srtxzmt;
@property (nonatomic, copy) NSString * _Nullable tax_on_fee;
@property (nonatomic, copy) NSString * _Nullable tcdadjustprice;
@property (nonatomic, copy) NSString * _Nullable tcdaet;
@property (nonatomic, copy) NSString * _Nullable tcdaft;
@property (nonatomic, copy) NSString * _Nullable tcdamt;
@property (nonatomic, copy) NSString * _Nullable tcdcalculator;
@property (nonatomic, copy) NSString * _Nullable tcdmsrp;
@property (nonatomic, copy) NSString * _Nullable tcdmsrplabel;
@property (nonatomic, copy) NSString * _Nullable tcdpcd;
@property (nonatomic, copy) NSString * _Nullable tcdpdctext;
@property (nonatomic, copy) NSString * _Nullable tcdper;
@property (nonatomic, copy) NSString * _Nullable tcdpil;
@property (nonatomic, copy) NSString * _Nullable tcdpwdpradjustopt;
@property (nonatomic, copy) NSString * _Nullable tcdsavmsg;
@property (nonatomic, copy) NSString * _Nullable tcdsavmsglable;
@property (nonatomic, copy) NSString * _Nullable tcdsb;
@property (nonatomic, copy) NSString * _Nullable tcdsd;
@property (nonatomic, copy) NSString * _Nullable tcdskipitem;
@property (nonatomic, copy) NSString * _Nullable tcdtaxonfee;
@property (nonatomic, copy) NSString * _Nullable tcdtdebcash;
@end


SWIFT_CLASS_NAMED("FEEPRFDB")
@interface FEEPRFDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface FEEPRFDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable w_fee;
@property (nonatomic, copy) NSString * _Nullable wo_fee;
@end


SWIFT_CLASS_NAMED("HBDB")
@interface HBDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface HBDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSDate * _Nullable hbTimeStamp;
@end


SWIFT_CLASS_NAMED("HOSTCONFIGDB")
@interface HOSTCONFIGDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface HOSTCONFIGDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable payurl;
@property (nonatomic, copy) NSString * _Nullable portalport;
@property (nonatomic, copy) NSString * _Nullable portalurl;
@property (nonatomic, copy) NSString * _Nullable sensepassurl;
@property (nonatomic, copy) NSString * _Nullable socketsensepassurl;
@property (nonatomic, copy) NSString * _Nullable steamport;
@property (nonatomic, copy) NSString * _Nullable steamurl;
@property (nonatomic, copy) NSString * _Nullable txnport;
@property (nonatomic, copy) NSString * _Nullable txnurl;
@end


SWIFT_CLASS_NAMED("INTEGDB")
@interface INTEGDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface INTEGDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable authtoken;
@property (nonatomic, copy) NSString * _Nullable brnchid;
@property (nonatomic, copy) NSString * _Nullable clntid;
@property (nonatomic, copy) NSString * _Nullable clntsertid;
@property (nonatomic, copy) NSString * _Nullable cryptopago;
@property (nonatomic, copy) NSString * _Nullable gifthost;
@property (nonatomic, copy) NSString * _Nullable mrchntid;
@property (nonatomic, copy) NSString * _Nullable qrcode;
@property (nonatomic, copy) NSString * _Nullable sanpass;
@property (nonatomic, copy) NSString * _Nullable sanpasstyp;
@property (nonatomic, copy) NSString * _Nullable sensepasstimeout;
@property (nonatomic, copy) NSString * _Nullable typintg;
@end


SWIFT_CLASS_NAMED("MISCDB")
@interface MISCDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class NSObject;

@interface MISCDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable app_download_timer;
@property (nonatomic, copy) NSString * _Nullable com_timeout;
@property (nonatomic, copy) NSString * _Nullable cust_logo;
@property (nonatomic, copy) NSString * _Nullable dsl_timer;
@property (nonatomic, copy) NSString * _Nullable e_promo_id;
@property (nonatomic, copy) NSString * _Nullable e_rcpt_img_url;
@property (nonatomic, copy) NSString * _Nullable e_rcpt_msg;
@property (nonatomic, copy) NSString * _Nullable e_rcpt_titl;
@property (nonatomic, copy) NSString * _Nullable e_rcpt_url;
@property (nonatomic, copy) NSString * _Nullable logourl;
@property (nonatomic, copy) NSString * _Nullable m_pass_set;
@property (nonatomic, copy) NSString * _Nullable p_promo_id;
@property (nonatomic, copy) NSString * _Nullable pap_rcpt_msg;
@property (nonatomic, copy) NSString * _Nullable pap_rcpt_titl;
@property (nonatomic, copy) NSString * _Nullable pap_rcpt_url;
@property (nonatomic, copy) NSString * _Nullable promo_id;
@property (nonatomic, copy) NSString * _Nullable qrtimer;
@property (nonatomic, copy) NSString * _Nullable sc_idl_timer;
@property (nonatomic, strong) NSObject * _Nullable sostype;
@property (nonatomic, copy) NSString * _Nullable sttl_tme_ot;
@property (nonatomic, copy) NSString * _Nullable trw_time;
@property (nonatomic, copy) NSString * _Nullable warn_msg;
@end


SWIFT_CLASS_NAMED("RECEIPTDB")
@interface RECEIPTDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface RECEIPTDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, strong) NSObject * _Nullable cr_c;
@property (nonatomic, copy) NSString * _Nullable dis;
@property (nonatomic) BOOL email;
@property (nonatomic, copy) NSString * _Nullable f1;
@property (nonatomic, copy) NSString * _Nullable f2;
@property (nonatomic, copy) NSString * _Nullable h1;
@property (nonatomic, copy) NSString * _Nullable h2;
@property (nonatomic, copy) NSString * _Nullable h3;
@property (nonatomic, copy) NSString * _Nullable h4;
@property (nonatomic) BOOL sms;
@end


SWIFT_CLASS_NAMED("REVERSALSTATUSDB")
@interface REVERSALSTATUSDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface REVERSALSTATUSDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable appFlowLog;
@property (nonatomic, copy) NSString * _Nullable lastTxnStatus;
@property (nonatomic, copy) NSString * _Nullable reversalAttemptCount;
@property (nonatomic, copy) NSString * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable tpn;
@property (nonatomic, copy) NSString * _Nullable traceNo;
@property (nonatomic, copy) NSString * _Nullable txRefNo;
@end


SWIFT_CLASS_NAMED("SETLDB")
@interface SETLDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface SETLDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable settleop;
@property (nonatomic, copy) NSString * _Nullable sm;
@end


SWIFT_CLASS_NAMED("SignatureUploadParam")
@interface SignatureUploadParam : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface SignatureUploadParam (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable additionalnntrymode;
@property (nonatomic, copy) NSString * _Nullable aid;
@property (nonatomic, copy) NSString * _Nullable aifname;
@property (nonatomic, copy) NSString * _Nullable amount;
@property (nonatomic, copy) NSString * _Nullable appname;
@property (nonatomic, copy) NSString * _Nullable baseimage;
@property (nonatomic, copy) NSString * _Nullable batchnum;
@property (nonatomic, copy) NSString * _Nullable buildnumber;
@property (nonatomic, copy) NSString * _Nullable cardNumber;
@property (nonatomic, copy) NSString * _Nullable cardType;
@property (nonatomic, copy) NSString * _Nullable commmedia;
@property (nonatomic, copy) NSString * _Nullable customfeelabel;
@property (nonatomic, copy) NSString * _Nullable customField;
@property (nonatomic, copy) NSString * _Nullable dateTime;
@property (nonatomic, copy) NSString * _Nullable description_;
@property (nonatomic, copy) NSString * _Nullable devicemodelId;
@property (nonatomic, copy) NSString * _Nullable discfabel;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable entrylegend;
@property (nonatomic, copy) NSString * _Nullable hTxId;
@property (nonatomic, copy) NSString * _Nullable inventoryCardArrayString;
@property (nonatomic, copy) NSString * _Nullable inventoryItems;
@property (nonatomic, copy) NSString * _Nullable invoiceNo;
@property (nonatomic) BOOL isibs;
@property (nonatomic, copy) NSString * _Nullable itemDetails;
@property (nonatomic, copy) NSString * _Nullable localtaxLabel;
@property (nonatomic, copy) NSString * _Nullable merchantfeefabel;
@property (nonatomic, copy) NSString * _Nullable paymenttype;
@property (nonatomic, copy) NSString * _Nullable phonenumber;
@property (nonatomic, copy) NSString * _Nullable pinstatus;
@property (nonatomic, copy) NSString * _Nullable postype;
@property (nonatomic, copy) NSString * _Nullable refundpolicy1;
@property (nonatomic, copy) NSString * _Nullable refundpolicy2;
@property (nonatomic, copy) NSString * _Nullable rrn;
@property (nonatomic, copy) NSString * _Nullable selectedPayment;
@property (nonatomic, copy) NSString * _Nullable statetaxLabel;
@property (nonatomic, copy) NSString * _Nullable surveyans;
@property (nonatomic, copy) NSString * _Nullable surveyquest;
@property (nonatomic, copy) NSString * _Nullable taglabel;
@property (nonatomic, copy) NSString * _Nullable tagvalue;
@property (nonatomic, copy) NSString * _Nullable tpn;
@property (nonatomic, copy) NSString * _Nullable traceNo;
@property (nonatomic, copy) NSString * _Nullable transactionType;
@property (nonatomic, copy) NSString * _Nullable transType;
@property (nonatomic, copy) NSString * _Nullable txduration;
@property (nonatomic, copy) NSString * _Nullable txid;
@property (nonatomic, copy) NSString * _Nullable txRefNo;
@property (nonatomic) BOOL uploadStatus;
@property (nonatomic, copy) NSString * _Nullable verficationline1;
@property (nonatomic, copy) NSString * _Nullable verificationline2;
@end


SWIFT_CLASS_NAMED("TIPTAXDB")
@interface TIPTAXDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface TIPTAXDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable ltax;
@property (nonatomic, copy) NSString * _Nullable max_ta;
@property (nonatomic, copy) NSString * _Nullable max_tp;
@property (nonatomic, copy) NSString * _Nullable s1;
@property (nonatomic, copy) NSString * _Nullable s2;
@property (nonatomic, copy) NSString * _Nullable s3;
@property (nonatomic, copy) NSString * _Nullable s4;
@property (nonatomic, copy) NSString * _Nullable stax;
@property (nonatomic, copy) NSString * _Nullable tax;
@property (nonatomic, copy) NSString * _Nullable tax1lable;
@property (nonatomic, copy) NSString * _Nullable tax2lable;
@property (nonatomic, copy) NSString * _Nullable taxmcr;
@property (nonatomic, copy) NSString * _Nullable taxppr;
@property (nonatomic, copy) NSString * _Nullable tip;
@property (nonatomic, copy) NSString * _Nullable tip_typ;
@property (nonatomic, copy) NSString * _Nullable ts_pap;
@property (nonatomic, copy) NSString * _Nullable ts_pos;
@end


SWIFT_CLASS_NAMED("TRANSACTIONDB")
@interface TRANSACTIONDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface TRANSACTIONDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable avs;
@property (nonatomic, copy) NSString * _Nullable batchpassword;
@property (nonatomic, strong) NSObject * _Nullable card_type;
@property (nonatomic, copy) NSString * _Nullable preauthpassword;
@property (nonatomic, copy) NSString * _Nullable presalepassword;
@property (nonatomic, copy) NSString * _Nullable printsavemsg;
@property (nonatomic, copy) NSString * _Nullable refundpassword;
@property (nonatomic, copy) NSString * _Nullable reportpassword;
@property (nonatomic, copy) NSString * _Nullable reprintpassword;
@property (nonatomic, copy) NSString * _Nullable save_msg_lbl;
@property (nonatomic, copy) NSString * _Nullable sl;
@property (nonatomic, copy) NSString * _Nullable ss;
@property (nonatomic, copy) NSString * _Nullable ticketpassword;
@property (nonatomic, copy) NSString * _Nullable tipadjustpassword;
@property (nonatomic, strong) NSObject * _Nullable tx_mode;
@property (nonatomic, strong) NSObject * _Nullable tx_type;
@property (nonatomic, copy) NSString * _Nullable upgradepassword;
@property (nonatomic, copy) NSString * _Nullable voidpassword;
@end



SWIFT_CLASS_NAMED("VALADDDB")
@interface VALADDDB : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface VALADDDB (SWIFT_EXTENSION(IposgoSDK))
@property (nonatomic, copy) NSString * _Nullable cussurv;
@property (nonatomic, copy) NSString * _Nullable invdefault;
@property (nonatomic, copy) NSString * _Nullable invibs;
@property (nonatomic, copy) NSString * _Nullable savetageach;
@property (nonatomic, copy) NSString * _Nullable sur_q;
@property (nonatomic, copy) NSString * _Nullable taginvoicekey;
@property (nonatomic, copy) NSString * _Nullable taginvoiceno;
@property (nonatomic, copy) NSString * _Nullable taginvoiceopt;
@property (nonatomic, copy) NSString * _Nullable taglabl;
@property (nonatomic, copy) NSString * _Nullable taglablkey;
@property (nonatomic, copy) NSString * _Nullable taglablopt;
@property (nonatomic, copy) NSString * _Nullable tagtableid;
@property (nonatomic, copy) NSString * _Nullable tagtablekey;
@property (nonatomic, copy) NSString * _Nullable tagtableopt;
@property (nonatomic, copy) NSString * _Nullable tagtx;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
